<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Thursday 28th of May 2015 06:06:18 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://childpass.local.optimuspro.ru:8086/site/oauth",

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "884167945398-8l26mg1nblifmjeqhai41rkgm39beq1u.apps.googleusercontent.com", "secret" => "0VRyZdYezaeU6c2s36ljpfhj" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "1592825660989378", "secret" => "05ddb618aca69ca3e52447f33398b714" ),
				"scope"   => "email, publish_actions",
				"popup"	  => true
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "O0uCwoVYfXmphyxT8pAu4EdCD", "secret" => "nPZ9zsyb3ah8v3OI2q0u79rcZwLaxXSyEwP0uvhA8lsi3Zky5x" ),
				//"oauth_token" =>
				//"keys"    => array ( "key" => "231257772-yBRCTTnxHUl5AJbkTv5gWK7kfOBiTUOXRGIXISEG", "secret" => "U149fmBROLOSK9crvSf2G1p9As4zdcYHqb6jNgFSfZygV" )
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "77b39b2bf2jdb0", "secret" => "ciDA5mAXue2Bpr8S" ),
				//"scope"	  => "w_share, r_basicprofile, r_emailaddress"
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => true,

		"debug_file" => "/home/lnkr-a/haouth.log"
	);
