<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Thursday 28th of May 2015 06:06:18 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://childpass.local.optimuspro.ru:8086/site/oauth",

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "1091484789374-r9k3m2qb8b0uk1lb8d3uj58eubvt55gb.apps.googleusercontent.com", "secret" => "cf7Qpw9rf1-VRyOiG6b-FLq1" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "1592498387688772", "secret" => "65aecd8013da60452d42d8845e0cc4c3" ),
				"scope"   => "email, publish_actions",
				"popup"	  => true
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "pUKrdYVypqRkUM8dWibSHEtRH", "secret" => "zK0YuSaPUAHTor8KLzJTmJ7OTo5jYWkF46NdIydP8ckOJY32sy" ),
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "77b39b2bf2jdb0", "secret" => "ciDA5mAXue2Bpr8S" ),
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => true,

		"debug_file" => Yii::app()->basePath . "/../runtime/hoauth.log"
	);
